global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'crypto-resolver'
    static_configs:
      - targets: ['resolver:8080']
  
  - job_name: 'crypto-blockchain-listener'
    static_configs:
      - targets: ['blockchain-listener:8080']
  
  - job_name: 'crypto-dns-server'
    static_configs:
      - targets: ['dns-server:8443']
  
  - job_name: 'crypto-worker-api'
    static_configs:
      - targets: ['worker-api:3000']
